<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="PDF4DEV.Components.PDF4NET.View.NET.Wpf" Version="16.3.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Annotations.Circle.png" />
    <Resource Include="Resources\Annotations.CloudPolygon.png" />
    <Resource Include="Resources\Annotations.CloudSquare.png" />
    <Resource Include="Resources\Annotations.Edit.png" />
    <Resource Include="Resources\Annotations.FileAttachment.png" />
    <Resource Include="Resources\Annotations.FreeText.png" />
    <Resource Include="Resources\Annotations.Hyperlink.png" />
    <Resource Include="Resources\Annotations.Ink.png" />
    <Resource Include="Resources\Annotations.Line.png" />
    <Resource Include="Resources\Annotations.Polygon.png" />
    <Resource Include="Resources\Annotations.Polyline.png" />
    <Resource Include="Resources\Annotations.RubberStamp.png" />
    <Resource Include="Resources\Annotations.Square.png" />
    <Resource Include="Resources\Annotations.Text.png" />
    <Resource Include="Resources\File.Annotations.png" />
    <Resource Include="Resources\File.Close.png" />
    <Resource Include="Resources\File.FitWidth.png" />
    <Resource Include="Resources\File.Forms.png" />
    <Resource Include="Resources\File.Open.png" />
    <Resource Include="Resources\File.PanAndScan.png" />
    <Resource Include="Resources\File.Save.png" />
    <Resource Include="Resources\File.SelectContent.png" />
    <Resource Include="Resources\FindNext.png" />
    <Resource Include="Resources\FindPrevious.png" />
    <Resource Include="Resources\FormDesigner.AlignBottom.png" />
    <Resource Include="Resources\FormDesigner.AlignCenter.png" />
    <Resource Include="Resources\FormDesigner.AlignLeft.png" />
    <Resource Include="Resources\FormDesigner.AlignMiddle.png" />
    <Resource Include="Resources\FormDesigner.AlignRight.png" />
    <Resource Include="Resources\FormDesigner.AlignTop.png" />
    <Resource Include="Resources\FormDesigner.CenterBoth.png" />
    <Resource Include="Resources\FormDesigner.CenterHorizontally.png" />
    <Resource Include="Resources\FormDesigner.CenterVertically.png" />
    <Resource Include="Resources\FormDesigner.DistributeHorizontally.png" />
    <Resource Include="Resources\FormDesigner.DistributeVertically.png" />
    <Resource Include="Resources\FormDesigner.MakeSameHeight.png" />
    <Resource Include="Resources\FormDesigner.MakeSameWidth.png" />
    <Resource Include="Resources\FormDesigner.MakeSameWidthAndHeight.png" />
    <Resource Include="Resources\FormField.Button.png" />
    <Resource Include="Resources\FormField.CheckBox.png" />
    <Resource Include="Resources\FormField.ComboBox.png" />
    <Resource Include="Resources\FormField.Edit.png" />
    <Resource Include="Resources\FormField.ListBox.png" />
    <Resource Include="Resources\FormField.RadioButton.png" />
    <Resource Include="Resources\FormField.Signature.png" />
    <Resource Include="Resources\FormField.TextBox.png" />
    <Resource Include="Resources\Layout.SingleColumn.png" />
    <Resource Include="Resources\Layout.SingleRow.png" />
    <Resource Include="Resources\MatchAccent.png" />
    <Resource Include="Resources\MatchCase.png" />
    <Resource Include="Resources\MatchWholeWord.png" />
    <Resource Include="Resources\RegularExpression.png" />
    <Resource Include="Resources\Search.png" />
    <Resource Include="Resources\Text.Highlight.png" />
    <Resource Include="Resources\Text.Squiggly.png" />
    <Resource Include="Resources\Text.Strikeout.png" />
    <Resource Include="Resources\Text.Underline.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Delete.png" />
    <Resource Include="Resources\Thumbnails.Rotate90CCW.png" />
    <Resource Include="Resources\Thumbnails.Rotate90CW.png" />
    <Resource Include="Resources\Tab.Thumbnails.png" />
  </ItemGroup>

</Project>